### ISSUE TITLE
Incorrect monitor shown in 2 monitor setup

### ISSUE THREAD

**Issue by khendrickx** [KeesjanVe/Desktop_Viewport#1]
Great tool, thanks for the effort!

I run into problems when using a 2 monitor setup
Steps to reproduce:
* Run Desktop_Viewport on primary monitor
* Press Button1
* The VLC window will now display the contents of your secondary monitor

**Comment by KeesjanVe** [comment]
I am not able to reproduce this problem. The application is tested on a dual monitor system and this problem did not arise.
I uploaded a new version of the application. This version shows the screen coordinates of the form. Maybe this will give a clue why your second desktop is shown instead of the first desktop.

The only reasons I can think of why the contents of the second monitor is shown:
- the second monitor is the primary display monitor
- the desktop is mirrored (same desktop on 2 monitors) and not extended (extend the desktop over 2 monitors)
- you are using some kind of 'multiple desktops' software or 'virtual desktop' software

If none of the above, I have no clue!
Maybe the new coordinates information can shine some light on the situation.

If you can give me more details about the problem and maybe a screenshot of the new 'Desktop viewport' application with the form coordinates details I will look into it.

**Comment by khendrickx** [comment]
Hi,
I experimented a bit further, seems the key to reproduce is to have the secondary monitor at the left:

* Monitor 1 is primary
* Monitor 2 is extended
* Monitor 2 is positioned on the left

**Comment by KeesjanVe** [comment]
Version 2.0.0.2 should address the issue with a primary monitor on the right and sharing content from the left side monitor.
Please confirm if this version resolves your issue.

**Comment by khendrickx** [comment]
Indeed, problem seems to be resolved now. Thanks for the fix!
